adarshpvmalkapur/adarshpvmalkapur/Controllers/AssociateOrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website.Controllers
{
    public class AssociateOrganizationController : Controller
    {
        // GET: AssociateOrganization
        public ActionResult shree_malaidevi_patasanstha()
        {
            return View();
        }

        public ActionResult samaj_prabodhan_sarvajnik_vachanaly()
        {
            return View();
        }

        public ActionResult vidnyan_prabodhani()
        {
            return View();
        }

        public ActionResult anand_vidyarthi_grahak_bhandar()
        {
            return View();
        }

        public ActionResult yashavant_fhale_fhule_bhajipala_sahakari_sanstha()
        {
            return View();
        }

        public ActionResult jamana_sahakari_grahak_sanstha()
        {
            return View();
        }

        public ActionResult karad_taluka_amateur_athletic_association()
        {
            return View();
        }
    }
}

adarshpvmalkapur/adarshpvmalkapur/Views/AssociateOrganization/anand_vidyarthi_grahak_bhandar.cshtml
@{
    ViewBag.Title = "आनंद विद्यार्थी सह.ग्राहक भांडार मर्या; मलकापूर";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}


<div class="full-widht-bread">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <nav aria-label="breadcrumb-sm">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">मुखपृष्ठ</a></li>
                        <li class="breadcrumb-item">@Html.ActionLink("सहयोगी संस्था", "AssociateOrganization", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="full-widht-pagedata">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <h5 class="card-header">@ViewBag.Title</h5>
                    <img class="card-img-top" src="~/img/titleImg.png" alt="@ViewBag.Title" title="@ViewBag.Title">
                    <div class="card-body">
                        <h5 class="card-title">
                            @ViewBag.Title
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>दि.३०/१०/१९८६</span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">नोंदणी.क्र.</span>
                            <span>एस.ए.टी./के आर डी/सी ओ एन/७२५/१९८६-८७ </span>
                        </p>

                        <p class="card-text text-justify">
                            विद्यार्थ्यांना ग्राहक भांडारमार्फत सर्व शैक्षणिक साहित्य अल्प दरात उपलब्ध करून दिले जाते.
                        </p>
                        @*<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

adarshpvmalkapur/adarshpvmalkapur/Views/AssociateOrganization/jamana_sahakari_grahak_sanstha.cshtml
@{
    ViewBag.Title = "जमना सहकारी ग्राहक संस्था मर्यादित,मलकापूर";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}


<div class="full-widht-bread">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <nav aria-label="breadcrumb-sm">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">मुखपृष्ठ</a></li>
                        <li class="breadcrumb-item">@Html.ActionLink("सहयोगी संस्था", "AssociateOrganization", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="full-widht-pagedata">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <h5 class="card-header">@ViewBag.Title</h5>
                    <img class="card-img-top" src="~/img/titleImg.png" alt="@ViewBag.Title" title="@ViewBag.Title">
                    <div class="card-body">
                        <h5 class="card-title">
                            @ViewBag.Title (श्री. लक्ष्मीदेवी शेतकरी मंडळ, मलकापूर सातारा जिल्हा मध्यवर्ती बँक लि; व नाबार्ड योजना पुरस्कृत)
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>०१/११/१९९०</span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">रजि.न.</span>
                            <span>एस.टी / के.आर.डी/सि.ओ.एन. / ७०१/९० </span>
                        </p>

                        <p class="card-text text-justify">
                            संस्थेच कार्यक्षेत्र मलकापूर व तिचे ५ कि.मी परिसरातील असून संस्थेची स्थापना नागरिकांनी जीवनावश्यक वस्तू सरकारमान्य रास्त भावात उपलब्ध करून देण्याच्या उदेशाने झाली आहे. संस्थेची स्वतंत्र अशी स्वामालकीची इमारत आहे. संस्थेच्या विकाससाठी संचालक मंडळ सतत कार्यरत असून संस्थेस ऑडिट वर्ग अ मिळाला आहे.संस्थेने चालू वर्षी शेतकर्‍याकडील शाळू विक्री चालू केली आहे. संस्थेकडे सध्या भागभांडवल रुपये २३६८०/- इतके असून संस्थेची गुंतवणूक रुपये १५६३१७/- इतकी आहे. सभासद संख्या ११६९आहे. संस्थेस या वर्षी एकूण नफा रुपये २४३१०७/- इतका झाला आहे.राखीव व इतर निधी ३६४७००/- व ईमारत २६५३२० इतका आहे.
                        </p>
                        @*<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

adarshpvmalkapur/adarshpvmalkapur/Views/AssociateOrganization/karad_taluka_amateur_athletic_association.cshtml
@{
    ViewBag.Title = "आदर्श क्रीडा संस्था, कराड व कराड तालुका  अॅमॅच्युअर  अॅथलेटिक्स असो.कराड";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}
<div class="full-widht-bread">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <nav aria-label="breadcrumb-sm">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">मुखपृष्ठ</a></li>
                        <li class="breadcrumb-item">@Html.ActionLink("सहयोगी संस्था", "AssociateOrganization", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="full-widht-pagedata">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <h5 class="card-header">@ViewBag.Title</h5>
                    <img class="card-img-top" src="~/img/titleImg.png" alt="@ViewBag.Title" title="@ViewBag.Title">
                    <div class="card-body">
                        <h5 class="card-title">
                            आदर्श क्रीडा संस्था ,कराड
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>दि.८/१०/१९९१ </span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">नोंदणी.क्र.</span>
                            <span>महा/२०८६/ सातारा  </span>
                        </p>
                        <p>
                            आदर्श क्रीडा संस्थाही यशस्वी खेळाडू निर्माण करणारी अल्पावधीत नावारूपास आलेली संस्था आहे.आदर्श क्रीडा संस्थेमार्फत संस्थेच्या विविध विद्यालयातील व समजतील उत्तम खेळाडूंची निवड करून त्यांना तज्ञ प्रशिक्षकामार्फत त्यांच्या आवडीनुसार मार्गदर्शन केले जाते. शिक्षक व विद्यार्थ्यांसाठी योग प्रशिक्षण व सुर्यनमस्कार प्रशिक्षण वर्ग राबविले जातात. लहान मुलांना स्पर्धेची आवड निर्माण होण्यासाठी बालवाडी ते १० वी पर्यंतच्या विध्यर्थ्यांसाठी रोडरेस,सस्सीखेच,व्हॅलीबोल,बुद्धिबळ,वेटलिफ्टिंग, चालणे अशा विविध स्पर्धा घेतल्या जातात.वर्षभरात खेळाडूंना मार्गदर्शन करण्यासाठी राष्ट्रीय स्तरावरील खेळाडुंचे मार्गदर्शन केले जाते.
                        </p>

                        <h5 class="card-title">
                            कराड व कराड तालुका  अॅमॅच्युअर  अॅथलेटिक्स असो.कराड
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>दि.२१/०१/१९९९  </span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">नोंदणी.क्र.</span>
                            <span>महा/५३४०१/ सातारा </span>
                        </p>


                        <p class="card-text text-justify">
                            ही यशस्वी खेळाडू निर्माण करणारी अल्पावधीत नावारूपास आलेली नोंदनीकृत संस्था आहे.ही संघटना सातारा जिल्हा अॅमॅच्युअर अॅथलेटिक्स असोसिएशन सलग्न असून सदर संघटनेद्वारे जिल्ह्यातील तालुक्यातील गुणवान खेळाडूंना खेळाचे व्यासपीठ उपलब्ध करून देण्याचे महत्वपूर्ण काम करते. यासाठी जिल्हास्तरीय सब्ज्युनियर स्पर्धा सयोजन आंतर्राष्ट्रीय व राष्ट्रीय खेळाडू सत्कार, क्रीडा पत्रकारिता परिसवाद इत्यादी कार्यक्रमांचे यशस्वी आयोजन केले जाते.चालू क्रीडा वर्षी दि १ जुन २०१७ रोजी शेतकर्‍यांच्या वेदना, अडचणी समजून आम्ही शेतकर्‍यांबरोबर आहोत. हे दाखवून देण्यासाठी “रन फॉर फार्मर्स” या स्पर्धेचे संघटना सयोजन करणार आहे.
                        </p>
                        <p class="card-text text-justify">
                            <b>शारीरिक शिक्षणाचे महत्व:</b> २१ शतकातील अहवणे पेलण्यासाठी बौद्धिक विकसा बरोबर शारीरिकदृष्ट्या सक्षम नागरिक तयार करणे ही काळाची गरज आहे. मानसिक बौद्धिक तान तनावमुळे विद्यार्थ्यांच्या आरोग्यावर विपरीत परिणाम होत आहे. खेळामुळे व्यायाम घडून येतो शारीरिक क्षमता वडते, मानसिक आरोग्य सुधारते निरोगी शरीरात निकोप मन वास करण्यास मदत होते. शरीर सधृड होते,खिलाडूवृत्ती वाढते.
                        </p>
                        <p class="card-text text-justify">
                            <b>उद्दिष्टे:</b> राष्ट्रीय व आंतरराष्ट्रीय दर्जाचे खेळाडू तयार करणे योग्य खेळ निवडण्यास मदत करणे क्रीडविषयक चर्चासत्रे ,परिषदा ,प्रदर्शन,परीसावाद,व्याखानेविडिओ क्रीडाशो,
                            प्रश्नमंजुषा ,मान्यवर मासिके ,वर्तमानपत्रे ई.सेवा पुरवणे आंतरराष्ट्रीय,आंतरराज्य, आंतरजिल्हा स्तरावर विविध खेळांच्या सांदर्भातील नियम व नियमावली यांची माहिती खेळाडूंना करून देणे.

                        </p>
                        @*<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

adarshpvmalkapur/adarshpvmalkapur/Views/AssociateOrganization/samaj_prabodhan_sarvajnik_vachanaly.cshtml
@{
    ViewBag.Title = "समाज प्रबोधन सार्वजनिक वाचनालय, मलकापूर";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}

<div class="full-widht-bread">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <nav aria-label="breadcrumb-sm">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">मुखपृष्ठ</a></li>
                        <li class="breadcrumb-item">@Html.ActionLink("सहयोगी संस्था", "AssociateOrganization", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="full-widht-pagedata">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <h5 class="card-header">@ViewBag.Title</h5>
                    <img class="card-img-top" src="~/img/titleImg.png" alt="@ViewBag.Title" title="@ViewBag.Title">
                    <div class="card-body">
                        <h5 class="card-title">
                            @ViewBag.Title
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>१२/०८/१९९२</span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">नोंदणी.क्र.</span>
                            <span>महा/एफ-२६६१/सातारा </span>
                        </p>

                        <p class="card-text text-justify">
                            मलकापूर मधील ग्रामसतांचा मागणी नुसार नगरपंचायत मलकापूर या ठिकाणी दि.१२/०८/१९९२ रोजी सुसज्ज ग्रंथालयाची स्थापना करण्यात आली. ग्रंथालय ब वर्ग दर्जा प्राप्त असून एकूण ११००० ग्रंथ संपदा आहे.तसेच ग्रंथालयात २८ नियतकालिके व १२ दैनिके घेतले जातात. वाचकासाठी बालविभाग , व महिला विभाग स्वतंत्र आहेत.सध्या ग्रंथालयाचे आजीव सभासद ३५०असून वार्षिक सभासद ३०० आहेत ग्रंथालयाचा माध्यमातून विधयरथ्य साथी गीतगायन,कथाकथन ,वक्तृत्व,निबंध स्पर्धा अशा स्पर्धांचे आयोजन केले जाते.
                            
                        </p>
                        <p class="card-text text-justify">
                            वाचनालयाचे महत्व : ज्ञान संपादनाची अनेक द्वारे आहेत. त्यापैकि वचन हे अत्यंत महत्वाचे आहे.वाचनाचे २ प्रकार आहेत . 
                            एक स्वतसाठी एक दुसर्‍यासाठी. जगातील सर्व माहिती वाचनाने प्राप्त होते.वचन विचार अवलोकन संवाद ही ज्ञान संपादनाची सदाणे आहेत. वचनाणे वैचारिक प्रगल्भता वाढते.वचन हे प्रभावी साधन आहे. जो वाचेल तो वाचेल या उक्ती प्रमाणे मानुषणे रोज सदग्रंथांचे वचन केले तर त्याचे व्यक्तिमहत्व प्रभावी बनेल त्या व्यक्ति जीवनात यशस्वी होण्यास मदत होएल म्हणून वाचनाचे महत्व फार मोठे आहे.
                        </p>
                        @*<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

adarshpvmalkapur/adarshpvmalkapur/Views/AssociateOrganization/shree_malaidevi_patasanstha.cshtml
@{
    ViewBag.Title = "श्री मळाईदेवी नागरी सहकारी पतसंस्था मर्यादित, जखिनवाडी ता.कराड";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}

<div class="full-widht-bread">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <nav aria-label="breadcrumb-sm">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">मुखपृष्ठ</a></li>
                        <li class="breadcrumb-item">@Html.ActionLink("सहयोगी संस्था", "AssociateOrganization", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="full-widht-pagedata">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <h5 class="card-header">@ViewBag.Title</h5>
                    <img class="card-img-top" src="~/img/titleImg.png" alt="@ViewBag.Title" title="@ViewBag.Title">
                    <div class="card-body">
                        <h5 class="card-title">
                            @ViewBag.Title
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>२१-०७-८७</span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">नोंदणी.क्र.</span>
                            <span>सात/केआरडी/आरएसआर/सीआर / ७४४</span>
                        </p>
                        <p class="card-text text-justify">
                            ||सुपथ सहकार अगछ्या||
                        </p>
                        <p class="card-text ">
                            <b>शाखा विस्तार</b>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <td>
                                            अ.क्र.
                                        </td>
                                        <td>
                                            शाखा
                                        </td>
                                        <td>
                                            पत्ता
                                        </td>
                                        <td>
                                            संपर्क
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr><td>१. </td><td>मुख्य कार्यालय </td><td> फोन(०२१६४)२४२०८२ मो.९५६१०००९१२ </td><td>पुना’-बेंगलोर रोड,थोरतमाळा,जखिनवाडी ता.कराड</td></tr>
                                    <tr><td>२.  </td><td>शाखा जखिनवाडी </td><td> फोन(०२१६४)२४२११७ </td><td>मळाईदेवी मंदिराजवळ, जखिनवाडी ता.कराड</td></tr>
                                    <tr><td>३.  </td><td>शाखा शास्त्रीनगर </td><td></td><td> भारती बँकेसमोर शास्त्रीनगर- मलकापूर</td></tr>
                                    <tr><td>४.  </td><td>शाखा-आगशिवनगर </td><td> फोन-९५१०००९२२ </td><td>इंद्रप्रस्थ कॉलनी, आगशिवनगर-मालकापूर</td></tr>
                                    <tr><td>५.  </td><td>शाखा-कसरशिरंबे </td><td> फोन-९५१०००९१८ </td><td> कसरशिरंबे ता.कराड</td></tr>
                                    <tr><td>६..  </td><td>शाखा कराड </td><td> फोन-९५१०००९२४  </td><td>मळाई टवेर्स, एच-४७ कोल्हापूर नाका,कराड </td></tr>
                                    <tr><td>७.  </td><td>शाखा-वसंतगड </td><td>फोन-९५१०००९२६ </td><td>वसंतगड ता.कराड  </td></tr>
                                    <tr><td>८.  </td><td>शाखा- मलकापूर </td><td> फोन-(०२१६४)२४३५८२ ९५१०००९१४ </td><td> भारती विद्यापीठासमोर, मालकापूर-कराड</td></tr>
                                    <tr><td>९.  </td><td>शाखा-वडोली निळेश्वर </td><td> फोन-९५१०००९३० </td><td> निळेश्वर मंदिराजवळ वडोली निळेश्वर ता.कराड.</td></tr>
                                    <tr><td>१०.  </td><td>शाखा मार्केट यार्ड </td><td> फोन-९५१०००९३५ </td><td> स्वा.सौ.शमराव पाटील फळे व भाजीपाला मार्केट समोर</td></tr>
                                    <tr><td>११.  </td><td>शाखा कोडोली </td><td> फोन-७०४०२८१३३४ </td><td> सा जि.म.बँकेजवळ, कोडोली ता.कराड</td></tr>
                                    <tr><td>१२.  </td><td>शाखा विद्यानगर </td><td> फोन-९५१०००९३२ </td><td>एस जी एम कॉलेजसमोर, विद्यानगर-सैदापूर</td></tr>
                                    <tr><td> १३. </td><td>शाखा-वाठार </td><td> फोन-९५१०००९३९ </td><td>एस.टी स्टँड जवळ वाठार ता.कराड</td></tr>
                                    <tr><td>१४.  </td><td>शाखा चरेगाव </td><td> फोन ९५१०००९२८ </td><td> मारुती मंदिराजवळ, चरेगाव, ता.कराड</td></tr>
                                    <tr><td>१५.  </td><td>शाखा सोमवार </td><td>फोन ९५१०००९३४ </td><td>पेठ कन्या शाळेजवळ, सोमवार पेठ,कराड </td></tr>
                                    <tr><td>१६.  </td><td>शाखा नंदलापूर  </td><td>फोन ९५१०००९३७</td><td>विस्तारीत कक्ष</td></tr>
                                    <tr><td>१७.  </td><td>शाखा केसे   </td><td>फोन ९५१०००९४१</td><td>विस्तारीत कक्ष</td></tr>
                                    <tr><td>१८.  </td><td>शाखा आगशिवनगर  </td><td> फोन ९५१०००९१३</td><td> विस्तारीत कक्ष</td></tr>
                                    <tr><td>१९.  </td><td>शाखा कोयनावसाहत    </td><td>फोन ७०२८०६७००५</td><td>विस्तारीत कक्ष</td></tr>
                                </tbody>
                            </table>
                        </p>
                        <p class="card-text ">
                            <br />
                            <br />
                            <br />
                           
                            <b> यशस्वी वाटचालीच्या पाऊलखुणा</b> 
                            
                            <table class="table table-bordered">
                                <tbody>
                                    <tr><td class="table-primary"> भागभांडवल </td> <td> ६.१० कोटी </td></tr>
                                    <tr><td class="table-primary"> ठेवीडवल </td> <td> ९७.२० कोटी </td> </tr>
                                    <tr><td class="table-primary"> कर्जे </td> <td> ६६ कोटी </td> </tr>
                                    <tr><td class="table-primary"> नफा </td> <td> ८७लाख </td> </tr>
                                    <tr><td class="table-primary"> सभासद </td> <td> ५५६३ </td> </tr>
                                    <tr><td class="table-primary"> शाखा </td> <td> १५+४ विस्तारीत कक्ष </td> </tr>
                                    <tr><td class="table-primary"> सेवक वर्ग </td> <td> ६५ </td> </tr>

                                </tbody>
                            </table>
                        </p>
                        @*<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

adarshpvmalkapur/adarshpvmalkapur/Views/AssociateOrganization/vidnyan_prabodhani.cshtml
@{
    ViewBag.Title = "विज्ञान प्रबोधीनी, कराड - मलकापूर";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}

<div class="full-widht-bread">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <nav aria-label="breadcrumb-sm">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">मुखपृष्ठ</a></li>
                        <li class="breadcrumb-item">@Html.ActionLink("सहयोगी संस्था", "AssociateOrganization", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="full-widht-pagedata">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <h5 class="card-header">@ViewBag.Title</h5>
                    <img class="card-img-top" src="~/img/titleImg.png" alt="@ViewBag.Title" title="@ViewBag.Title">
                    <div class="card-body">
                        <h5 class="card-title">
                            @ViewBag.Title
                        </h5>
                        <p class="card-text">
                            <span class="font-weight-bold">स्थापना दि.</span>
                            <span>दि.१९/०८/१९९४</span>
                        </p>
                        <p class="card-text">
                            <span class="font-weight-bold">नोंदणी.क्र.</span>
                            <span>महा/३७४६/सातारा  </span>
                        </p>

                        <p class="card-text text-justify">
                            विद्यार्थी व सर्वसामान्य लोकांच्यात वैज्ञानिक दृष्टीकोण जागृत करण्यासाठी विज्ञान प्रबोधीनी या संस्थेची स्थापना करण्यात आली. संस्थेचे ११ संचालक व २२५ सभासद आहेत . विज्ञान प्रबोधीनी या संस्थे मार्फत बीजारोपन ,वृक्षारोपण हे उपक्रम राबवले जातात.तसेच फटाके विरहित प्रदूषण मुक्त दिवाळी साजरी केली जाते.कै.पांडुरंग पुजारी स्मृति दीना निमित्ता शक्षणिक साहित्य निर्मिती केली जाते. तसेच प्रगटशील शेतकरी व पशू पालक यांचा सत्कार केला जातो. पर्यावरण व वसुंधरा दिन साजरे केले जातात. अंधश्रद्धा निर्मूलनासाठी विविध प्रात्यक्षिके तसेच व्यसन मुक्तीसाठी जाणीव जागृती फेरी व तज्ञ व्यक्तींची व्याख्याने आयोजित केली जातात. नालबंडिंग ५० बंधारे बांधण्यात आले,पर्यावरण संरक्षण ,निबंध,चित्रकला स्पर्धांचे विज्ञान छंद मंडळा मार्फत आयोजन केले जाते.तसेच जखिनवाडी हद्दीत १० वनराई बंधारे बांधण्यात आले आहेत.वन संरक्षणासाठी वनवा बचाव उपक्रमा अंतर्गत घोष वाक्य फलक झाडांना लावण्यात आले आहेत.पक्षांसाठी चारपाणी उपक्रम राबवण्यात येतात.पायी चला,निरोगी रहा हा संदेश समाजामध्ये पोहचवण्यासाठी विद्यार्थ्यांची रॅली काढण्यात आली.
                        </p>
                        <p class="card-text text-justify">
                            श्री.मळाई ग्रुपच्या वतीने आयोजित केलेल्या रक्तदान शिबिरात उत्स्फूर्तपणे २१४ राक्तदात्यांनी रक्तदान केले. इन्सपायर अवॉर्ड स्पर्धेत पर्यावरण पूरक जे सी बी या उपकरणाने राज्यस्तरीय स्पर्धेत सहभाग घेतला.

                        </p>
                        @*<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>